-- Ejecutar conectado como ECOMMERCE.

INSERT INTO USER_ACCOUNTS (USERNAME, EMAIL, ROLE, ACTIVE) VALUES ('admin', 'admin@ecommerce.dev', 'ADMIN', 1);
INSERT INTO USER_ACCOUNTS (USERNAME, EMAIL, ROLE, ACTIVE) VALUES ('buyer01', 'buyer01@ecommerce.dev', 'CUSTOMER', 1);
INSERT INTO USER_ACCOUNTS (USERNAME, EMAIL, ROLE, ACTIVE) VALUES ('support01', 'support@ecommerce.dev', 'SUPPORT', 1);

INSERT INTO PRODUCTS (NAME, CATEGORY, PRICE, ACTIVE) VALUES ('Laptop Pro 14', 'Computing', 1499.99, 1);
INSERT INTO PRODUCTS (NAME, CATEGORY, PRICE, ACTIVE) VALUES ('Auriculares Wireless', 'Audio', 129.90, 1);

INSERT INTO INVENTORY_ITEMS (PRODUCT_ID, QUANTITY, WAREHOUSE_CODE) VALUES (1, 25, 'WH-BOG-01');
INSERT INTO INVENTORY_ITEMS (PRODUCT_ID, QUANTITY, WAREHOUSE_CODE) VALUES (2, 80, 'WH-MDE-01');

INSERT INTO CART_ITEMS (USER_ID, PRODUCT_ID, QUANTITY) VALUES (2, 1, 1);
INSERT INTO CART_ITEMS (USER_ID, PRODUCT_ID, QUANTITY) VALUES (2, 2, 2);

INSERT INTO SALES_ORDERS (USER_ID, STATUS, TOTAL) VALUES (2, 'CREATED', 1759.79);

INSERT INTO PAYMENT_TRANSACTIONS (ORDER_ID, AMOUNT, STATUS) VALUES (1, 1759.79, 'PENDING');

INSERT INTO SHIPMENTS (ORDER_ID, CARRIER, STATUS) VALUES (1, 'DHL', 'PENDING');

INSERT INTO REVIEWS (PRODUCT_ID, RATING, COMMENT_TEXT) VALUES (1, 5, 'Excelente equipo, muy rapido.');

INSERT INTO CAMPAIGNS (CODE, DISCOUNT_PERCENT, ACTIVE) VALUES ('WELCOME10', 10, 1);

COMMIT;
