spring.application.name=users
server.port=8083
server.servlet.context-path=/users

# H2 Database Settings
spring.datasource.url=jdbc:h2:mem:userdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# API Documentation
springdoc.api-docs.path=/openapi
springdoc.swagger-ui.path=/docs
