-- Ejecutar como SYS o un usuario con privilegios de DBA.
-- Ajusta la password antes de ejecutar.

CREATE USER ECOMMERCE IDENTIFIED BY ecommerce_123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO ECOMMERCE;
GRANT CREATE TABLE TO ECOMMERCE;
GRANT CREATE VIEW TO ECOMMERCE;
GRANT CREATE SEQUENCE TO ECOMMERCE;
GRANT CREATE TRIGGER TO ECOMMERCE;
GRANT CREATE PROCEDURE TO ECOMMERCE;
