spring.application.name=cart
server.port=8084
server.servlet.context-path=/cart

# --- Configuracion ORACLE CLOUD ---
spring.datasource.url=jdbc:oracle:thin:@ecomerce_high?TNS_ADMIN=/app/wallet
spring.datasource.username=ADMIN
spring.datasource.password=ecomerceDuocUc123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- JPA / HIBERNATE ---
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# 'update' creara¡ la tabla 'cart_items' en el esquema al arrancar.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger / OpenAPI
springdoc.api-docs.path=/openapi
springdoc.swagger-ui.path=/docs

# Configuracion de Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nachincastor@gmail.com
spring.mail.password=uxqgdjoohzmkfjgu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- Microservice URLs ---
product.service.url=http://localhost:8082
user.service.url=http://localhost:8081
