spring.application.name=cart
server.port=8084
server.servlet.context-path=/cart
springdoc.api-docs.path=/openapi
springdoc.swagger-ui.path=/docs

# H2 DB config in-memory cache.
spring.datasource.url=jdbc:h2:mem:cartdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.datasource.generate-unique-name=false

# JPA / Hibernate configuration.
# "update" creates tables automatically when @Entity classes are detected.
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# Shows SQL queries in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
